parameters:
#    acme_default.example.class: Acme\DefaultBundle\Example
    global_base.class: Acme\DefaultBundle\Services\global_base

services:
#    acme_default.example:
#        class: %acme_default.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    global_base_services:
        class: Acme\DefaultBundle\Services\GlobalBaseService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"